#!/usr/bin/env zsh

iDIR="$HOME/.config/mako/icons"
notifTime=500

expVal=2

# Get brightness
get_backlight() {
  val=$(brightnessctl g)
  maxLight=$(brightnessctl m)
  LIGHT=$(printf "%.0f\n" "$(((1.0 * val / maxLight) ** (1.0 / expVal) * 100))")
  echo "${LIGHT}"
}

# Get icons
get_icon() {
  current="$(get_backlight)"
  if [[ ("$current" -ge "0") && ("$current" -le "19200") ]]; then
    icon="$iDIR/brightness-20.png"
  elif [[ ("$current" -ge "19200") && ("$current" -le "38400") ]]; then
    icon="$iDIR/brightness-40.png"
  elif [[ ("$current" -ge "38400") && ("$current" -le "57600") ]]; then
    icon="$iDIR/brightness-60.png"
  elif [[ ("$current" -ge "57600") && ("$current" -le "76800") ]]; then
    icon="$iDIR/brightness-80.png"
  elif [[ ("$current" -ge "76800") && ("$current" -le "96000") ]]; then
    icon="$iDIR/brightness-100.png"
  fi
}

# Notify
notify_user() {
  light=$(get_backlight)
  notify-send \
    -t $notifTime \
    -a sys-notify \
    -h string:x-canonical-private-synchronous:sys-notify \
    -h int:value:"$light" \
    -u low \
    -i "$icon" \
    ""
}

# Increase brightness
inc_backlight() {
  brightnessctl --exponent=$expVal set +5% && get_icon && notify_user
}

# Decrease brightness
dec_backlight() {
  brightnessctl -n20 --exponent=$expVal set 5%- && get_icon && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
  get_backlight
elif [[ "$1" == "--inc" ]]; then
  inc_backlight
elif [[ "$1" == "--dec" ]]; then
  dec_backlight
else
  get_backlight
fi
