#!/usr/bin/bash

if [ -z "$FOOT_SPAWNED" ]; then
  FOOT_SPAWNED=1 exec foot "$0" "$@"
fi

tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
yazi "$@" --cwd-file="$tmp"
IFS= read -r -d '' cwd <"$tmp"
[ "$cwd" != "$PWD" ] && [ -d "$cwd" ] && builtin cd -- "$cwd" || builtin true
command rm -f -- "$tmp"

exec zsh
