$image = /home/leo/Pictures/Wallpapers/spidermanstreet.png

$background = rgba(1a120eff)

$error = rgba(ffece9ff)

$error_container = rgba(ffaea4ff)

$inverse_on_surface = rgba(000000ff)

$inverse_primary = rgba(723818ff)

$inverse_surface = rgba(f0dfd8ff)

$on_background = rgba(f0dfd8ff)

$on_error = rgba(000000ff)

$on_error_container = rgba(000000ff)

$on_primary = rgba(000000ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(000000ff)

$on_primary_fixed_variant = rgba(240900ff)

$on_secondary = rgba(000000ff)

$on_secondary_container = rgba(000000ff)

$on_secondary_fixed = rgba(000000ff)

$on_secondary_fixed_variant = rgba(1f0c04ff)

$on_surface = rgba(ffffffff)

$on_surface_variant = rgba(ffffffff)

$on_tertiary = rgba(000000ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(000000ff)

$on_tertiary_fixed_variant = rgba(141100ff)

$outline = rgba(ffece5ff)

$outline_variant = rgba(d3beb6ff)

$primary = rgba(ffece5ff)

$primary_container = rgba(ffb08aff)

$primary_fixed = rgba(ffdbcbff)

$primary_fixed_dim = rgba(ffb693ff)

$scrim = rgba(000000ff)

$secondary = rgba(ffece5ff)

$secondary_container = rgba(e2baa8ff)

$secondary_fixed = rgba(ffdbcbff)

$secondary_fixed_dim = rgba(e6beacff)

$shadow = rgba(000000ff)

$source_color = rgba(bd581dff)

$surface = rgba(1a120eff)

$surface_bright = rgba(594e49ff)

$surface_container = rgba(382e2aff)

$surface_container_high = rgba(443934ff)

$surface_container_highest = rgba(50443fff)

$surface_container_low = rgba(271e1aff)

$surface_container_lowest = rgba(000000ff)

$surface_dim = rgba(1a120eff)

$surface_tint = rgba(ffb693ff)

$surface_variant = rgba(52443dff)

$tertiary = rgba(fbf1b6ff)

$tertiary_container = rgba(ccc48cff)

$tertiary_fixed = rgba(ede4aaff)

$tertiary_fixed_dim = rgba(d0c890ff)

