$image = /home/leo/Pictures/Wallpapers/gloomy_landscape.jpg

$background = rgba(0f1416ff)

$error = rgba(ffece9ff)

$error_container = rgba(ffaea4ff)

$inverse_on_surface = rgba(000000ff)

$inverse_primary = rgba(004f5fff)

$inverse_surface = rgba(dee3e6ff)

$on_background = rgba(dee3e6ff)

$on_error = rgba(000000ff)

$on_error_container = rgba(000000ff)

$on_primary = rgba(000000ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(000000ff)

$on_primary_fixed_variant = rgba(001419ff)

$on_secondary = rgba(000000ff)

$on_secondary_container = rgba(000000ff)

$on_secondary_fixed = rgba(000000ff)

$on_secondary_fixed_variant = rgba(001419ff)

$on_surface = rgba(ffffffff)

$on_surface_variant = rgba(ffffffff)

$on_tertiary = rgba(000000ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(000000ff)

$on_tertiary_fixed_variant = rgba(090e2cff)

$outline = rgba(e9f1f5ff)

$outline_variant = rgba(bbc4c7ff)

$primary = rgba(d8f5ffff)

$primary_container = rgba(81cee4ff)

$primary_fixed = rgba(afecffff)

$primary_fixed_dim = rgba(85d2e8ff)

$scrim = rgba(000000ff)

$secondary = rgba(dbf4fdff)

$secondary_container = rgba(aec7cfff)

$secondary_fixed = rgba(cee7efff)

$secondary_fixed_dim = rgba(b2cbd3ff)

$shadow = rgba(000000ff)

$source_color = rgba(345660ff)

$surface = rgba(0f1416ff)

$surface_bright = rgba(4b5153ff)

$surface_container = rgba(2c3133ff)

$surface_container_high = rgba(373c3eff)

$surface_container_highest = rgba(42484aff)

$surface_container_low = rgba(1b2022ff)

$surface_container_lowest = rgba(000000ff)

$surface_dim = rgba(0f1416ff)

$surface_tint = rgba(85d2e8ff)

$surface_variant = rgba(40484bff)

$tertiary = rgba(efeeffff)

$tertiary_container = rgba(bcc0e7ff)

$tertiary_fixed = rgba(dee0ffff)

$tertiary_fixed_dim = rgba(c0c4ebff)

