$image = /home/leo/Pictures/Wallpapers/sunset_field.jpg

$background = rgba(191114ff)

$error = rgba(ffece9ff)

$error_container = rgba(ffaea4ff)

$inverse_on_surface = rgba(000000ff)

$inverse_primary = rgba(6e3553ff)

$inverse_surface = rgba(eedfe3ff)

$on_background = rgba(eedfe3ff)

$on_error = rgba(000000ff)

$on_error_container = rgba(000000ff)

$on_primary = rgba(000000ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(000000ff)

$on_primary_fixed_variant = rgba(2a0019ff)

$on_secondary = rgba(000000ff)

$on_secondary_container = rgba(000000ff)

$on_secondary_fixed = rgba(000000ff)

$on_secondary_fixed_variant = rgba(1e0b15ff)

$on_surface = rgba(ffffffff)

$on_surface_variant = rgba(ffffffff)

$on_tertiary = rgba(000000ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(000000ff)

$on_tertiary_fixed_variant = rgba(210b00ff)

$outline = rgba(ffebf1ff)

$outline_variant = rgba(d0bec4ff)

$primary = rgba(ffebf1ff)

$primary_container = rgba(f9acd0ff)

$primary_fixed = rgba(ffd8e7ff)

$primary_fixed_dim = rgba(fdb0d4ff)

$scrim = rgba(000000ff)

$secondary = rgba(ffebf1ff)

$secondary_container = rgba(dcb9c7ff)

$secondary_fixed = rgba(fdd9e7ff)

$secondary_fixed_dim = rgba(e0bdcbff)

$shadow = rgba(000000ff)

$source_color = rgba(6a314fff)

$surface = rgba(191114ff)

$surface_bright = rgba(574d51ff)

$surface_container = rgba(372e31ff)

$surface_container_high = rgba(42393cff)

$surface_container_highest = rgba(4e4448ff)

$surface_container_low = rgba(251d21ff)

$surface_container_lowest = rgba(000000ff)

$surface_dim = rgba(191114ff)

$surface_tint = rgba(fdb0d4ff)

$surface_variant = rgba(504348ff)

$tertiary = rgba(ffece3ff)

$tertiary_container = rgba(eeb796ff)

$tertiary_fixed = rgba(ffdbc8ff)

$tertiary_fixed_dim = rgba(f2bb99ff)

