# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#ffffff"

# Title color for boxes
theme[title]="#ffece5"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#ffece5"

# Background color of selected item in processes box
theme[selected_bg]="#ffece5"

# Foreground color of selected item in processes box
theme[selected_fg]="#000000"

# Color of inactive/disabled text
theme[inactive_fg]="#ffffff"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#fbf1b6"

# Cpu box outline color
theme[cpu_box]="#ffece5"

# Memory/disks box outline color
theme[mem_box]="#ffece5"

# Net up/down box outline color
theme[net_box]="#ffece5"

# Processes box outline color
theme[proc_box]="#ffece5"

# Box divider line and small boxes line color
theme[div_line]="#d3beb6"

# Temperature graph colors
theme[temp_start]="#ffece5"
theme[temp_mid]="#ffece5"
theme[temp_end]="#ffece9"

# CPU graph colors
theme[cpu_start]="#ffece5"
theme[cpu_mid]="#ffece5"
theme[cpu_end]="#ffece9"

# Mem/Disk free meter
theme[free_start]="#ffece5"
theme[free_mid]=""
theme[free_end]="#e2baa8"

# Mem/Disk cached meter
theme[cached_start]="#fbf1b6"
theme[cached_mid]=""
theme[cached_end]="#ccc48c"

# Mem/Disk available meter
theme[available_start]="#ffece5"
theme[available_mid]=""
theme[available_end]="#ffb08a"

# Mem/Disk used meter
theme[used_start]="#ffece9"
theme[used_mid]=""
theme[used_end]="#ffaea4"

# Download graph colors
theme[download_start]="#ffece5"
theme[download_mid]="#ffece5"
theme[download_end]="#fbf1b6"

# Upload graph colors
theme[upload_start]="#ffece5"
theme[upload_mid]="#ffece5"
theme[upload_end]="#fbf1b6"